-- ====================================================
-- CLASSROOM RESERVATION SYSTEM - EERD BASED SCHEMA
-- ====================================================

CREATE TABLE IF NOT EXISTS DEPARTMENT(
    DEPT_ID     SERIAL,
    DEPT_NAME   VARCHAR(25)     NOT NULL,
    DEPT_CODE   VARCHAR(7)      NOT NULL    UNIQUE,

    CONSTRAINT DEPT_DEPT_ID_PK PRIMARY KEY(DEPT_ID)
);

CREATE TABLE IF NOT EXISTS COURSE(
    COURSE_CODE      VARCHAR(6)      NOT NULL,
    COURSE_NAME      VARCHAR(50)       NOT NULL    UNIQUE,
    CREDIT_HRS       INT              NOT NULL,

    CONSTRAINT COURSE_COURSE_CODE_PK PRIMARY KEY(COURSE_CODE)   
);

CREATE TABLE IF NOT EXISTS COURSES_OFFERED_IN_DEPTS(

    COURSE_CODE      VARCHAR(6)      NOT NULL,
    DEPT_ID          INT              NOT NULL,
    
    CONSTRAINT COID_PK PRIMARY KEY(COURSE_CODE,DEPT_ID), 
    CONSTRAINT COURSE_CODE_COID_FK FOREIGN KEY(COURSE_CODE) REFERENCES COURSE(COURSE_CODE),
    CONSTRAINT DEPT_ID_COID_FK FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
);

CREATE TABLE IF NOT EXISTS STAFF(
    USERNAME        VARCHAR(30)     NOT NULL    UNIQUE,
    PASSWORD_HASH   VARCHAR(255)    NOT NULL,
    STAFF_ROLE      VARCHAR(25)     NOT NULL    CHECK (STAFF_ROLE IN ('instructor', 'admin')),
    STAFF_ID        SERIAL           NOT NULL,
    FIRST_NAME      VARCHAR(25)     NOT NULL,
    LAST_NAME       VARCHAR(25)     NOT NULL,
    DEPT_ID         INT              NOT NULL,

    CONSTRAINT STAFF_ID_PK PRIMARY KEY(STAFF_ID),
    CONSTRAINT STAFF_DEPT_ID_FK FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
);

CREATE TABLE IF NOT EXISTS STAFF_PHONES(
    STAFF_ID        INT             NOT NULL,
    PHONE_NO        VARCHAR(12)     CHECK (PHONE_NO ~ '^[0-9+\-() ]+$'),
    CONSTRAINT STAFF_PHONES_PK PRIMARY KEY(STAFF_ID,PHONE_NO),
    CONSTRAINT STAFF_PHONES_FK FOREIGN KEY(STAFF_ID) REFERENCES STAFF(STAFF_ID)
);

CREATE TABLE IF NOT EXISTS STAFF_EMAILS(
    STAFF_ID         INT         NOT NULL,
    EMAILS           VARCHAR(100),

    CONSTRAINT STAFF_EMAILS_PK PRIMARY KEY(STAFF_ID,EMAILS),
    CONSTRAINT STAFF_EMAILS_FK FOREIGN KEY(STAFF_ID) REFERENCES STAFF(STAFF_ID)

);

CREATE TABLE IF NOT EXISTS INSTRUCTORS(
    STAFF_ID         INT         NOT NULL,
    STATUS_IN        BOOLEAN     NOT NULL,

    CONSTRAINT INSTRUCTORS_STAFF_ID_PK PRIMARY KEY(STAFF_ID),
    CONSTRAINT INSTRUCTORS_STAFF_ID_FK FOREIGN KEY(STAFF_ID) REFERENCES STAFF(STAFF_ID)

);

CREATE TABLE IF NOT EXISTS COURSES_TEACH(
    STAFF_ID        INT             NOT NULL,
    COURSE_CODE     VARCHAR(6),

    CONSTRAINT STAFF_ID_CT_PK PRIMARY KEY(STAFF_ID,COURSE_CODE),
    CONSTRAINT STAFF_ID_CT_FK FOREIGN KEY(STAFF_ID) REFERENCES INSTRUCTORS(STAFF_ID),
    CONSTRAINT COURSE_CT_FK FOREIGN KEY(COURSE_CODE) REFERENCES COURSE(COURSE_CODE)
);

CREATE TABLE IF NOT EXISTS TEACHING_DEPARTMENT(
    DEPT_ID         INT,
    STAFF_ID        INT             NOT NULL,

    CONSTRAINT STAFF_ID_TD_PK PRIMARY KEY(STAFF_ID,DEPT_ID),
    CONSTRAINT STAFF_ID_TD_FK FOREIGN KEY(STAFF_ID) REFERENCES INSTRUCTORS(STAFF_ID),
    CONSTRAINT DEPT_ID_TD_FK FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
);

CREATE TABLE IF NOT EXISTS SECTION(
    SECTION_ID      VARCHAR(6)     NOT NULL,
    YEAR_NO         INT             NOT NULL,
    SECTION_NO      VARCHAR(1)     NOT NULL,

    CONSTRAINT SECTION_PK PRIMARY KEY(SECTION_ID),
    CONSTRAINT SECTION_UNIQUE UNIQUE (YEAR_NO, SECTION_NO)
);

CREATE TABLE IF NOT EXISTS SECTION_COURSES (
    SECTION_ID      VARCHAR(6)  NOT NULL,
    COURSE_CODE     VARCHAR(6)  NOT NULL,

    CONSTRAINT SECTION_COURSES_PK PRIMARY KEY (SECTION_ID, COURSE_CODE),
    CONSTRAINT SECTION_COURSES_SECTION_FK FOREIGN KEY (SECTION_ID) REFERENCES SECTION(SECTION_ID),
    CONSTRAINT SECTION_COURSES_COURSE_FK FOREIGN KEY (COURSE_CODE) REFERENCES COURSE(COURSE_CODE)
); 

CREATE TABLE IF NOT EXISTS CLASSROOM(

    ROOM_NO         INT         NOT NULL,

    CONSTRAINT CLASSROOM_PK PRIMARY KEY(ROOM_NO)
);

CREATE TABLE IF NOT EXISTS TIMESLOT(

    SLOT_ID         INT         NOT NULL,
    STARTING_TIME   TIME        NOT NULL    UNIQUE,
    ENDING_TIME     TIME        NOT NULL    UNIQUE,

    CONSTRAINT TIMESLOT_PK PRIMARY KEY(SLOT_ID)
);

CREATE TABLE IF NOT EXISTS TIMETABLE (
    TIMETABLE_ID    SERIAL              NOT NULL,
    SECTION_ID      VARCHAR(6)         NOT NULL,
    COURSE_CODE     VARCHAR(6)         NOT NULL,
    STAFF_ID        INT                 NOT NULL,
    ROOM_NO         INT                 NOT NULL,
    SLOT_ID         INT                 NOT NULL,
    DAY_NO          VARCHAR(10)        NOT NULL,

    CONSTRAINT TIMETABLE_PK PRIMARY KEY (TIMETABLE_ID),
    CONSTRAINT TIMETABLE_SECTION_FK FOREIGN KEY (SECTION_ID) REFERENCES SECTION(SECTION_ID),
    CONSTRAINT TIMETABLE_COURSE_FK FOREIGN KEY (COURSE_CODE) REFERENCES COURSE(COURSE_CODE),
    CONSTRAINT TIMETABLE_STAFF_FK FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),
    CONSTRAINT TIMETABLE_ROOM_FK FOREIGN KEY (ROOM_NO) REFERENCES CLASSROOM(ROOM_NO),
    CONSTRAINT TIMETABLE_SLOT_FK FOREIGN KEY (SLOT_ID) REFERENCES TIMESLOT(SLOT_ID),
    CONSTRAINT TIMETABLE_UNIQUE UNIQUE (SECTION_ID, SLOT_ID, DAY_NO),
    CONSTRAINT TIMETABLE_DAY_CHK CHECK (DAY_NO IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'))
);

CREATE TABLE IF NOT EXISTS RESERVATION(
    RESERVATION_ID      SERIAL,
    RESERVED_DATE       DATE            NOT NULL,
    ROOM_ID             INT             NOT NULL,
    TIMESLOT_ID         INT             NOT NULL,
    CREATED_BY          INT             NOT NULL,
    TIME_OF_CREATION    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    SECTION_ID          VARCHAR(6)     NOT NULL,

    CONSTRAINT RESERVATION_ID_RESERVATION_PK PRIMARY KEY(RESERVATION_ID),
    CONSTRAINT ROOM_ID_RESERVATION_FK FOREIGN KEY(ROOM_ID) REFERENCES CLASSROOM(ROOM_NO),
    CONSTRAINT TIMESLOT_ID_RESERVATION_FK FOREIGN KEY(TIMESLOT_ID) REFERENCES TIMESLOT(SLOT_ID),
    CONSTRAINT SECTION_ID_RESERVATION_FK FOREIGN KEY(SECTION_ID) REFERENCES SECTION(SECTION_ID),
    CONSTRAINT CREATED_BY_RESERVATION_FK FOREIGN KEY(CREATED_BY) REFERENCES STAFF(STAFF_ID)
);

CREATE TABLE IF NOT EXISTS APPROVAL_REQUEST(
    APPROVAL_ID         SERIAL,
    APPROVAL_STATUS     VARCHAR(10)     CHECK(APPROVAL_STATUS IN ('pending','approved','rejected'))       NOT NULL,
    APPROVAL_TIME       TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    APPROVED_BY         INT              NOT NULL,
    RESERVATION_ID      INT              NOT NULL,
    
    CONSTRAINT APPROVAL_ID_APPROVAL_REQUEST_PK PRIMARY KEY(APPROVAL_ID),
    CONSTRAINT RESERVATION_ID_APPROVAL_REQUEST_FK FOREIGN KEY(RESERVATION_ID) REFERENCES RESERVATION(RESERVATION_ID),
    CONSTRAINT APPROVED_BY_APPROVAL_REQUEST_FK FOREIGN KEY(APPROVED_BY) REFERENCES STAFF(STAFF_ID) 
);

CREATE OR REPLACE VIEW TIMETABLE_GRID AS
SELECT 
    T.TIMETABLE_ID,
    T.DAY_NO,
    T.ROOM_NO,
    TS.STARTING_TIME,
    TS.ENDING_TIME,
    TS.SLOT_ID,
    C.COURSE_CODE,
    C.COURSE_NAME,
    S.FIRST_NAME || ' ' || S.LAST_NAME AS INSTRUCTOR_NAME,
    SEC.SECTION_ID
FROM TIMETABLE T
JOIN TIMESLOT TS ON T.SLOT_ID = TS.SLOT_ID
JOIN COURSE C ON T.COURSE_CODE = C.COURSE_CODE
JOIN STAFF S ON T.STAFF_ID = S.STAFF_ID
JOIN SECTION SEC ON T.SECTION_ID = SEC.SECTION_ID;

CREATE OR REPLACE VIEW PENDING_APPROVALS AS
SELECT 
    AR.APPROVAL_ID,
    AR.APPROVAL_STATUS,
    R.RESERVATION_ID,
    R.RESERVED_DATE,
    R.ROOM_ID,
    R.SECTION_ID,
    TS.STARTING_TIME,
    TS.ENDING_TIME,
    S.FIRST_NAME || ' ' || S.LAST_NAME AS REQUESTED_BY
FROM APPROVAL_REQUEST AR
JOIN RESERVATION R ON AR.RESERVATION_ID = R.RESERVATION_ID
JOIN TIMESLOT TS ON R.TIMESLOT_ID = TS.SLOT_ID
JOIN STAFF S ON R.CREATED_BY = S.STAFF_ID
WHERE AR.APPROVAL_STATUS = 'pending';